export const PHASE4_REQUIRED_CHECKS = Object.freeze([
  'TOOL_REGISTRATION',
  'TOOL_UNKNOWN_REJECTED',
  'INPUT_VALIDATION',
  'READ_TOOL',
  'WRITE_TOOL',
  'EXECUTION_FAILURE_ISOLATED',
  'VERIFICATION_FAILURE',
  'TIMEOUT',
  'UNAUTHORIZED_TOOL',
  'PHASE_2_REGRESSION',
  'PHASE_3_REGRESSION',
  'FULL_REGRESSION',
] as const);

export type Phase4RequiredCheck = typeof PHASE4_REQUIRED_CHECKS[number];
