import { useMemo, useState } from 'react';
import { earthquakeRisk, forecast } from '@analysis/probabilistic';
import { assessEvidence } from '@analysis/critical';
import { defaultCapabilities } from '@assistant/autonomy';
import { getRecentEarthquakes } from '@network/publicWeb';

const signals=[{name:'Actividad reciente',value:.62,weight:1.2},{name:'Tendencia histórica',value:.48},{name:'Cambio de régimen',value:.31,weight:.8},{name:'Señal secundaria',value:.22,weight:.6}];
const evidence=[{source:'Fuente A',claim:'Señal observada',reliability:.82},{source:'Fuente B',claim:'Interpretación alternativa',reliability:.58,contradicts:['Fuente A']}];
export default function IAC33App(){const [domain,setDomain]=useState<'earthquake'|'weather'|'conflict'>('earthquake');const [count,setCount]=useState<number|null>(null);const [status,setStatus]=useState('Sistema listo');const result=useMemo(()=>domain==='earthquake'?earthquakeRisk(signals):forecast(domain,signals,domain==='weather'?'7 días':'30 días'),[domain]);const critical=useMemo(()=>assessEvidence(evidence),[]);async function update(){setStatus('Consultando datos públicos…');try{const d=await getRecentEarthquakes();setCount(d.features.length);setStatus('Datos actualizados')}catch{setStatus('Fuente no disponible')}}return <main style={{maxWidth:1100,margin:'auto',padding:24,fontFamily:'system-ui',background:'#080b10',color:'#e8edf2',minHeight:'100vh'}}><header><h1>IAC33</h1><p>INTELIGENCIA · ANÁLISIS · VISIÓN CRÍTICA</p></header><section style={{display:'grid',gap:16,gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))'}}><article><h2>Red pública</h2><p>Internet: <b>ACTIVA</b></p><p>Datos satelitales públicos: <b>DISPONIBLES</b></p><button onClick={update}>Actualizar sismos</button>{count!==null&&<p>Eventos recibidos: {count}</p>}</article><article><h2>Proyecciones</h2><button onClick={()=>setDomain('earthquake')}>Sismos Chile</button> <button onClick={()=>setDomain('weather')}>Lluvias Chile</button> <button onClick={()=>setDomain('conflict')}>Conflictos</button><p>{result.horizon} · confianza {result.confidence}</p><ol>{result.scenarios.map(s=><li key={s.label}>{s.label}: <b>{Math.round(s.probability*100)}%</b></li>)}</ol><small>{result.warning}</small></article><article><h2>Pensamiento crítico</h2><p>Confianza: <b>{critical.overallConfidence}</b></p><p>Hechos {critical.facts.length} · Contradicciones {critical.contradictions.length} · Hipótesis {critical.hypotheses.length}</p></article><article><h2>Capacidades</h2><ul>{defaultCapabilities.map(c=><li key={c.id}>{c.name}</li>)}</ul></article></section><footer style={{marginTop:20}}>{status}</footer></main>}
