import { useMemo, type CSSProperties } from "react";
import { useTimelineStore } from "../timeline/timeline-store";
import type { TimelineClipPatch } from "../types/andrew-core";
const number = (value: string, fallback: number): number => Number.isFinite(Number(value)) ? Number(value) : fallback;
export default function ClipInspector(): JSX.Element {
  const state = useTimelineStore(); const clip = useMemo(() => state.clips.find((c) => c.id === state.selectedClipId), [state.clips, state.selectedClipId]);
  if (!clip) return <aside style={panel}><h2 style={heading}>Inspector</h2><p style={muted}>Selecciona un clip.</p></aside>;
  const update = (patch: TimelineClipPatch): void => state.updateClip(clip.id, patch); const t = clip.transform; const a = clip.adjustments;
  return <aside style={panel}><h2 style={heading}>Inspector</h2>
    {clip.type === "text" && <label style={label}>Texto<textarea style={input} value={clip.textContent} onChange={(e) => update({ textContent: e.target.value })}/></label>}
    <section style={section}><strong>Tiempo</strong><div style={grid}><label>Inicio<input style={input} type="number" min="0" step="0.01" value={clip.startTime} onChange={(e) => update({ startTime: Math.max(0, number(e.target.value, clip.startTime)) })}/></label><label>Duración<input style={input} type="number" min="0.01" step="0.01" value={clip.duration} onChange={(e) => update({ duration: Math.max(0.01, number(e.target.value, clip.duration)) })}/></label></div>
      {clip.type === "media" && <><label style={label}>Trim inicio<input style={input} type="number" min="0" step="0.01" value={clip.trimStart} onChange={(e) => update({ trimStart: Math.max(0, number(e.target.value, clip.trimStart)) })}/></label><label style={label}>Trim final<input style={input} type="number" min="0" step="0.01" value={clip.trimEnd} onChange={(e) => update({ trimEnd: Math.max(0, number(e.target.value, clip.trimEnd)) })}/></label></>}
    </section>
    <section style={section}><strong>Transformación</strong><div style={grid}><label>X<input style={input} type="number" value={t.x} onChange={(e) => update({ transform: { ...t, x: number(e.target.value, t.x) } })}/></label><label>Y<input style={input} type="number" value={t.y} onChange={(e) => update({ transform: { ...t, y: number(e.target.value, t.y) } })}/></label><label>Escala X<input style={input} type="number" min="0" step="0.01" value={t.scaleX} onChange={(e) => update({ transform: { ...t, scaleX: Math.max(0, number(e.target.value, t.scaleX)) } })}/></label><label>Escala Y<input style={input} type="number" min="0" step="0.01" value={t.scaleY} onChange={(e) => update({ transform: { ...t, scaleY: Math.max(0, number(e.target.value, t.scaleY)) } })}/></label></div><label style={label}>Rotación<input style={input} type="number" value={t.rotation} onChange={(e) => update({ transform: { ...t, rotation: number(e.target.value, t.rotation) } })}/></label></section>
    <section style={section}><strong>Ajustes</strong><label style={label}>Opacidad<input type="range" min="0" max="1" step="0.01" value={a.opacity} onChange={(e) => update({ adjustments: { ...a, opacity: Number(e.target.value) } })}/></label>{(["brightness", "contrast", "saturation"] as const).map((key) => <label style={label} key={key}>{key}<input style={input} type="number" min="0" step="0.01" value={a[key]} onChange={(e) => update({ adjustments: { ...a, [key]: Math.max(0, number(e.target.value, a[key])) } })}/></label>)}</section>
    <button style={danger} onClick={() => state.removeClip(clip.id)}>Eliminar clip</button>
  </aside>;
}
const panel: CSSProperties = { width: 280, minWidth: 240, padding: 16, background: "#101116", color: "#eee", overflowY: "auto", boxSizing: "border-box" }; const heading: CSSProperties = { fontSize: 16, margin: "0 0 16px" }; const muted: CSSProperties = { color: "#8b8d98", fontSize: 13 }; const label: CSSProperties = { display: "grid", gap: 6, fontSize: 12, color: "#aaa", marginTop: 10 }; const input: CSSProperties = { width: "100%", boxSizing: "border-box", background: "#191b22", border: "1px solid #30333d", borderRadius: 6, color: "#eee", padding: "7px 8px" }; const grid: CSSProperties = { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8 }; const section: CSSProperties = { borderTop: "1px solid #292c35", paddingTop: 12, marginTop: 14 }; const danger: CSSProperties = { width: "100%", marginTop: 18, padding: 9, border: 0, borderRadius: 6, background: "#8b2525", color: "#fff", cursor: "pointer" };
