import { useMemo, useRef, type CSSProperties, type PointerEvent as ReactPointerEvent } from "react";
import { useTimelineStore } from "../timeline/timeline-store";
import useTimelineDrag from "../hooks/useTimelineDrag";
const fmt = (s: number): string => `${Math.floor(s / 60)}:${String(Math.floor(s % 60)).padStart(2, "0")}`;
export default function TimelineUI(): JSX.Element {
  const state = useTimelineStore(); const ruler = useRef<HTMLDivElement>(null); const pps = 80 * state.zoom; const drag = useTimelineDrag({ pixelsPerSecond: pps, trackHeight: 52, snap: 1 / state.fps }); const tracks = useMemo(() => [...state.tracks].sort((a, b) => a.order - b.order), [state.tracks]);
  const seek = (event: ReactPointerEvent<HTMLDivElement>): void => { const rect = ruler.current?.getBoundingClientRect(); if (!rect) return; state.seek(Math.max(0, Math.min(state.duration, (event.clientX - rect.left) / pps))); };
  return <section style={root}><div style={toolbar}><button onClick={() => state.togglePlay()}>{state.playing ? "Pausa" : "Reproducir"}</button><button onClick={() => state.setCurrentTime(0)}>Inicio</button><span>{fmt(state.currentTime)} / {fmt(state.duration)}</span><label>Zoom <input type="range" min="0.25" max="4" step="0.05" value={state.zoom} onChange={(e) => state.setZoom(Number(e.target.value))}/></label></div><div ref={ruler} style={rulerStyle} onPointerDown={seek}>{Array.from({ length: Math.ceil(Math.max(1, state.duration)) + 1 }, (_, i) => <span key={i} style={{ position: "absolute", left: i * pps, fontSize: 10, color: "#777" }}>{i}s</span>)}<div style={{ ...playhead, left: state.currentTime * pps }}/></div><div style={tracksWrap}>{tracks.map((track) => <div key={track.id} style={trackRow}><div style={trackName}>{track.name}</div><div style={lane}>{state.clips.filter((clip) => clip.trackId === track.id).map((clip) => <button key={clip.id} onPointerDown={(e) => drag.onPointerDown(e, clip.id)} onClick={() => state.selectClip(clip.id)} style={{ ...clipStyle, width: Math.max(8, clip.duration * pps), left: clip.startTime * pps, outline: clip.id === state.selectedClipId ? "2px solid #fff" : "none" }}>{clip.type === "text" ? `T: ${clip.textContent}` : "Media"}</button>)}</div></div>)}</div></section>;
}
const root: CSSProperties = { background: "#0b0c10", color: "#eee", borderTop: "1px solid #292c35" }; const toolbar: CSSProperties = { height: 42, display: "flex", alignItems: "center", gap: 8, padding: "0 10px", borderBottom: "1px solid #24262e", fontSize: 12 }; const rulerStyle: CSSProperties = { position: "relative", height: 26, overflow: "hidden", background: "#11131a", borderBottom: "1px solid #24262e", minWidth: 1000 }; const playhead: CSSProperties = { position: "absolute", top: 0, bottom: 0, width: 2, background: "#fff", pointerEvents: "none" }; const tracksWrap: CSSProperties = { maxHeight: 300, overflow: "auto" }; const trackRow: CSSProperties = { display: "flex", height: 52, borderBottom: "1px solid #22252d" }; const trackName: CSSProperties = { width: 110, minWidth: 110, padding: 16, boxSizing: "border-box", fontSize: 11, color: "#aaa", background: "#12141a" }; const lane: CSSProperties = { position: "relative", flex: 1, minWidth: 1000 }; const clipStyle: CSSProperties = { position: "absolute", top: 7, height: 38, overflow: "hidden", whiteSpace: "nowrap", textOverflow: "ellipsis", border: "1px solid #505563", borderRadius: 5, background: "#252936", color: "#fff", fontSize: 11, cursor: "grab" };
