#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

echo "== Andrew2.0 / build:apk =="
echo "[1/7] Tests"
npm run test:run

echo "[2/7] Vite production build"
npm run build

echo "[3/7] Android platform"
if [[ ! -d android ]]; then
  npx cap add android
fi

# Keep the generated Android project deterministic. Do not touch application code.
APP_GRADLE="android/app/build.gradle"
if [[ ! -f "$APP_GRADLE" ]]; then
  echo "ERROR: $APP_GRADLE was not generated by Capacitor" >&2
  exit 2
fi

python3 - "$APP_GRADLE" <<'PY'
from pathlib import Path
import re, sys
p = Path(sys.argv[1])
s = p.read_text()
s = re.sub(r'applicationId\s+["\'][^"\']+["\']', 'applicationId "com.andrew.editor"', s, count=1)
s = re.sub(r'versionCode\s+\d+', 'versionCode 1', s, count=1)
s = re.sub(r'versionName\s+["\'][^"\']+["\']', 'versionName "1.0.0"', s, count=1)
if 'versionCode 1' not in s:
    s = re.sub(r'(defaultConfig\s*\{)', r'\1\n        versionCode 1\n        versionName "1.0.0"', s, count=1)
p.write_text(s)
PY

echo "[4/7] Capacitor sync"
npx cap sync android

echo "[5/7] Gradle clean + assembleDebug"
cd android
./gradlew clean
./gradlew assembleDebug --no-daemon

APK="app/build/outputs/apk/debug/app-debug.apk"
if [[ ! -s "$APK" ]]; then
  echo "ERROR: APK was not generated: $APK" >&2
  exit 3
fi

echo "[6/7] APK integrity checks"
if command -v apksigner >/dev/null 2>&1; then
  apksigner verify --verbose --print-certs "$APK"
fi
unzip -t "$APK" >/dev/null

echo "[7/7] APK generated and validated"
echo "APK: $ROOT_DIR/android/$APK"
echo "== build:apk completed =="
