export const AGENT_ERRORS = Object.freeze({
  PLANNER_FAILED: 'AGENT_PLANNER_FAILED',
  INVALID_TOOL_PLAN: 'AGENT_INVALID_TOOL_PLAN',
  TOOL_FAILED: 'AGENT_TOOL_FAILED',
  RESPONSE_VERIFICATION_FAILED: 'AGENT_RESPONSE_VERIFICATION_FAILED',
  TOOL_RESULT_VERIFICATION_FAILED: 'AGENT_TOOL_RESULT_VERIFICATION_FAILED',
  VERIFIER_FAILED: 'AGENT_VERIFIER_FAILED',
  MAX_ITERATIONS: 'AGENT_MAX_ITERATIONS',
} as const);
