import { ExportDimensions, ExportProgress, TimelineClip, VideoExportCallbacks, VideoExportOptions, VideoExportResult } from "../types/andrew-core";
import { useTimelineStore } from "../timeline/timeline-store";
import WebGLRenderer from "../renderer/WebGLRenderer";

interface RendererLike { resize(width?: number,height?: number):void; setTime(time:number):void; setClips(clips:readonly TimelineClip[]):void; render():void; dispose():void }
interface MediaRecorderConstructor { new(stream:MediaStream,options?:MediaRecorderOptions):MediaRecorder; isTypeSupported(type:string):boolean }
function getMediaRecorderConstructor():MediaRecorderConstructor|undefined{if(typeof window==="undefined"||!("MediaRecorder" in window))return undefined;return window.MediaRecorder as unknown as MediaRecorderConstructor}
function chooseMimeType(requested?:string):string{const C=getMediaRecorderConstructor();if(!C)return requested??"video/webm";const candidates=[requested,"video/webm;codecs=vp9","video/webm;codecs=vp8","video/webm","video/mp4"].filter((v):v is string=>typeof v==="string");return candidates.find(m=>C.isTypeSupported(m))??"video/webm"}
function getDimensions(options:VideoExportOptions):ExportDimensions{const width=Math.max(2,Math.floor(options.width??1920));const height=Math.max(2,Math.floor(options.height??1080));return{width:width%2===0?width:width-1,height:height%2===0?height:height-1}}
function nextAnimationFrame():Promise<void>{return new Promise(resolve=>requestAnimationFrame(()=>resolve()))}
function makeProgress(currentFrame:number,totalFrames:number,currentTime:number,duration:number):ExportProgress{const percentage=totalFrames<=1?100:Math.min(100,Math.max(0,currentFrame/Math.max(1,totalFrames-1)*100));return{currentFrame,totalFrames,percentage,currentTime,duration}}
function triggerDownload(blob:Blob,filename:string):void{const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=filename;anchor.style.display="none";document.body.appendChild(anchor);anchor.click();anchor.remove();window.setTimeout(()=>URL.revokeObjectURL(url),1000)}
function createDOMRenderer(dimensions:ExportDimensions):{canvas:HTMLCanvasElement;renderer:RendererLike}{const canvas=document.createElement("canvas");canvas.width=dimensions.width;canvas.height=dimensions.height;const context=canvas.getContext("webgl2",{alpha:false,antialias:true,preserveDrawingBuffer:true});if(!context)throw new Error("WebGL2 no está disponible para exportación.");const renderer=new WebGLRenderer(canvas) as unknown as RendererLike;renderer.resize(dimensions.width,dimensions.height);return{canvas,renderer}}
async function renderFrame(renderer:RendererLike,clips:readonly TimelineClip[],time:number):Promise<void>{renderer.setTime(time);renderer.setClips(clips);renderer.render();await nextAnimationFrame()}
async function exportWithMediaRecorder(renderer:RendererLike,canvas:HTMLCanvasElement,clips:readonly TimelineClip[],duration:number,fps:number,dimensions:ExportDimensions,options:VideoExportOptions,callbacks:VideoExportCallbacks,isCancelled:()=>boolean):Promise<VideoExportResult>{const mimeType=chooseMimeType(options.mimeType);const stream=canvas.captureStream(fps);const C=getMediaRecorderConstructor();if(!C)throw new Error("MediaRecorder no está disponible en este navegador.");const recorder=new C(stream,{mimeType,videoBitsPerSecond:options.bitrate??8000000});const chunks:BlobPart[]=[];const stopped=new Promise<void>((resolve,reject)=>{recorder.ondataavailable=e=>{if(e.data.size>0)chunks.push(e.data)};recorder.onerror=()=>reject(new Error("MediaRecorder produjo un error durante la exportación."));recorder.onstop=()=>resolve()});const totalFrames=Math.max(1,Math.ceil(duration*fps)+1);callbacks.onStatusChange?.("rendering");recorder.start(250);for(let frameIndex=0;frameIndex<totalFrames;frameIndex+=1){if(isCancelled()){if(recorder.state!=="inactive")recorder.stop();await stopped.catch(()=>undefined);throw new DOMException("Exportación cancelada.","AbortError")}const time=Math.min(duration,frameIndex/fps);await renderFrame(renderer,clips,time);callbacks.onProgress?.(makeProgress(frameIndex,totalFrames,time,duration))}if(recorder.state!=="inactive")recorder.stop();await stopped;const blob=new Blob(chunks,{type:mimeType});return{blob,mimeType,filename:options.filename??(mimeType.includes("mp4")?"andrew-export.mp4":"andrew-export.webm"),duration,width:dimensions.width,height:dimensions.height,fps,frames:totalFrames}}

export class VideoExporter { private cancelled=false;private exporting=false;cancel():void{this.cancelled=true}private isCancelled():boolean{return this.cancelled}async export(options:VideoExportOptions={},callbacks:VideoExportCallbacks={}):Promise<VideoExportResult>{if(this.exporting)throw new Error("Ya existe una exportación en curso.");this.exporting=true;this.cancelled=false;const state=useTimelineStore.getState();const fps=Math.max(1,Math.min(240,options.fps??state.fps));const duration=Math.max(0,state.duration);const clips=state.clips.map(clip=>({...clip}));const dimensions=getDimensions(options);let renderer:RendererLike|undefined;try{callbacks.onStatusChange?.("preparing");const environment=createDOMRenderer(dimensions);renderer=environment.renderer;const result=await exportWithMediaRecorder(renderer,environment.canvas,clips,duration,fps,dimensions,options,callbacks,()=>this.isCancelled());callbacks.onStatusChange?.("finalizing");callbacks.onProgress?.(makeProgress(result.frames,result.frames,duration,duration));callbacks.onStatusChange?.("completed");callbacks.onComplete?.(result);return result}catch(error){if(error instanceof DOMException&&error.name==="AbortError"){callbacks.onStatusChange?.("cancelled");throw error}const normalized=error instanceof Error?error:new Error(String(error));callbacks.onStatusChange?.("error");callbacks.onError?.(normalized);throw normalized}finally{renderer?.dispose();this.exporting=false}}
download(result:VideoExportResult):void{triggerDownload(result.blob,result.filename)}}
export const videoExporter=new VideoExporter();
export default videoExporter;
